apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: db
  type: {{ .Values.service.type }}
