replicaCount: 1

image:
  repository: techiescamp/pomodoro
  tag: "2.1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    http: 3000
    admin: 7000
    admin_nodeport: 30163
    metrics: 7100
    metrics_nodeport: 31106

configmap:
  mountpath: /app/config.js
  subpath: config.js

secretName: backend-secrets

## Network Policy
ingress:
  namespace: frontend
  appLabel: frontend
  port: 3000

egress:
  namespace: db
  appLabel: db
  port: 27017
