replicaCount: 1

image:
  repository: techiescamp/pomodoro
  tag: "4.0.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

configmap:
  mountpath: /app/src/config.js
  subpath: config.js

service:
  type: NodePort
  port: 3000
  nodeport: 32749

backend_url: http://34.71.163.101:30163

## Network Policy

egress:
  namespace: backend
  appLabel: backend
  port: 7000

autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
